name: N-Body Simulation CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-cpu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make python3 python3-pip
        pip3 install matplotlib

    - name: Build Sequential Version
      run: make seq

    - name: Build OpenMP Version
      run: make omp

    - name: Run Sequential Test
      run: ./nbody_seq sem 10 1000 10

    - name: Run OpenMP Test
      run: ./nbody_omp sem 10 1000 10

  build-gpu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install CUDA Toolkit
      run: |
        sudo apt-get update
        sudo apt-get install -y nvidia-cuda-toolkit make g++

    - name: Build CUDA Version
      run: make cuda
